
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xaa\xc6\xf7\xdf]\xe7>(\xb0\x19\xc9\x91t|\xcbg'
    
_lr_action_items = {'BOLD':([0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,18,19,],[-14,4,-1,-7,4,-2,-5,-6,4,4,-3,-9,-13,18,-8,-10,-12,-11,]),'NEWLINE':([0,1,2,3,5,6,8,9,11,12,13,15,16,18,19,],[-14,3,-1,-7,-2,-5,-6,-4,-3,-9,-13,-8,-10,-12,-11,]),'POUNDSIGN':([0,1,2,3,5,6,8,9,11,12,13,15,16,18,19,],[-14,7,-1,-7,-2,-5,-6,-4,-3,-9,-13,-8,-10,-12,-11,]),'LATICS':([0,1,2,3,4,5,6,8,9,10,11,12,13,15,16,17,18,19,],[-14,10,-1,-7,10,-2,-5,-6,10,10,-3,-9,-13,-8,-10,19,-12,-11,]),'SEPERATOR':([0,1,2,3,5,6,8,9,11,12,13,15,16,18,19,],[-14,8,-1,-7,-2,-5,-6,-4,-3,-9,-13,-8,-10,-12,-11,]),'CONTENTS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,18,19,],[-14,13,-1,-7,13,-2,-5,15,-6,13,13,-3,-9,-13,-8,-10,-12,-11,]),'$end':([0,1,2,3,5,6,8,9,11,12,13,15,16,18,19,],[-14,0,-1,-7,-2,-5,-6,-4,-3,-9,-13,-8,-10,-12,-11,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'all':([0,],[1,]),'title':([1,],[5,]),'newline':([1,],[6,]),'texts':([1,4,9,10,],[12,14,16,17,]),'paragraph':([1,],[9,]),'seperator':([1,],[11,]),'empty':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> all","S'",1,None,None,None),
  ('all -> empty','all',1,'p_all_empty','plyYacc.py',36),
  ('all -> all title','all',2,'p_all_title','plyYacc.py',40),
  ('all -> all seperator','all',2,'p_all_seperator','plyYacc.py',44),
  ('all -> all paragraph','all',2,'p_all_paragraph','plyYacc.py',48),
  ('all -> all newline','all',2,'p_all_newline','plyYacc.py',52),
  ('seperator -> SEPERATOR','seperator',1,'p_sep_seperator','plyYacc.py',58),
  ('newline -> NEWLINE','newline',1,'p_sep_newline','plyYacc.py',62),
  ('title -> POUNDSIGN CONTENTS','title',2,'p_title_poundsign','plyYacc.py',66),
  ('paragraph -> texts','paragraph',1,'p_paragraph_empty','plyYacc.py',72),
  ('paragraph -> paragraph texts','paragraph',2,'p_paragraph_texts','plyYacc.py',76),
  ('texts -> LATICS texts LATICS','texts',3,'p_texts_latics','plyYacc.py',80),
  ('texts -> BOLD texts BOLD','texts',3,'p_texts_bold','plyYacc.py',84),
  ('texts -> CONTENTS','texts',1,'p_texts_contents','plyYacc.py',88),
  ('empty -> <empty>','empty',0,'p_empty','plyYacc.py',92),
]
